export type Department = {
    id: string
    name: string
    acronym: string
    description: string
    dateCreated: string
    divisions: string[]
  }
  
  export const departmentData: Department[] = [
    {
      id: "723ed52f",
      name: "Office of the Governor",
      acronym: "GO",
      description: "This department is responsible for the overall governance of the province.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Governor's Office", "Administrative Division", "Finance Division"],
    },
    {
      id: "489e1d42",
      name: "Office of the Governor - Personal Staff",
      acronym: "GO-PS",
      description: "This department provides personal support to the Governor.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Personal Staff", "Security Detail", "Protocol Office"],
    },
    {
      id: "a762d9c0",
      name: "Office of the Vice Governor",
      acronym: "VGO",
      description: "This department supports the Vice Governor in their duties.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Vice Governor's Office", "Legislative Affairs", "Public Relations"],
    },
    {
      id: "b3f12e8d",
      name: "Office of the Vice Governor - Personal Staff",
      acronym: "VGO-PS",
      description: "This department provides personal support to the Vice Governor.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Personal Staff", "Security Detail", "Protocol Office"],
    },
    {
      id: "e9d71f6a",
      name: "Office of the Secretary to the Sangguniang Panlalawigan",
      acronym: "OSSP",
      description: "This department supports the Secretary to the Provincial Board.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Secretary's Office", "Legislative Research", "Committee Affairs"],
    },
    {
      id: "c4e5f6g7",
      name: "Bulacan Environment and Natural Resources Office",
      acronym: "BENRO",
      description: "This department is responsible for environmental conservation and natural resources management.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Environmental Conservation", "Natural Resources Management", "Research and Development"],
    },
    {
      id: "h8i9j0k1",
      name: "Bulacan Polytechnic College",
      acronym: "BPC",
      description: "This department provides technical education and training.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Academic Affairs", "Student Affairs", "Research and Extension"],
    },
    {
      id: "l2m3n4o5",
      name: "Provincial Accounting Office",
      acronym: "PAO",
      description: "This department handles the financial accounting and management of the province.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Financial Management", "Accounting Services", "Budget and Treasury"],
    },
    {
      id: "p6q7r8s9",
      name: "Provincial Administrator's Office",
      acronym: "PA's Office",
      description: "This department supports the Provincial Administrator in their duties.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Administrative Services", "Human Resource Management", "General Services"],
    },
    {
      id: "t0u1v2w3",
      name: "Provincial Agriculture Office",
      acronym: "PAO",
      description: "This department promotes agricultural development in the province.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Agricultural Development", "Farm-to-Market Road", "Agricultural Extension"],
    },
    {
      id: "x4y5z6a7",
      name: "Provincial Assessor's Office",
      acronym: "PAO",
      description: "This department is responsible for property assessment and taxation.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Property Assessment", "Taxation", "Real Property Appraisal"],
    },
    {
      id: "b8c9d0e1",
      name: "Provincial Budget Office",
      acronym: "PBO",
      description: "This department prepares and manages the provincial budget.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Budget Preparation", "Budget Execution", "Financial Planning"],
    },
    {
      id: "f2g3h4i5",
      name: "Provincial Civil Security and Jail Management Office",
      acronym: "PCSJMO",
      description: "This department is responsible for civil security and jail management.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Civil Security", "Jail Management", "Fire Protection"],
    },
    {
      id: "j6k7l8m9",
      name: "Provincial Cooperative and Enterprise Development Office",
      acronym: "PCEDO",
      description: "This department promotes cooperative and enterprise development.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Cooperative Development", "Enterprise Development", "Microfinance"],
    },
    {
      id: "n0o1p2q3",
      name: "Provincial Disaster Risk Reduction and Management Office",
      acronym: "PDRRMO",
      description: "This department is responsible for disaster risk reduction and management.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Disaster Risk Reduction", "Disaster Management", "Emergency Response"],
    },
    {
      id: "r4s5t6u7",
      name: "Provincial Engineer's Office",
      acronym: "PEO",
      description: "This department handles infrastructure development and maintenance.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Infrastructure Development", "Maintenance and Repair", "Engineering Services"],
    },
    {
      id: "v8w9x0y1",
      name: "Provincial General Services Office",
      acronym: "PGSO",
      description: "This department provides general services and support to the province.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["General Services", "Supply and Property Management", "Motor Pool"],
    },
    {
      id: "z2a3b4c5",
      name: "Provincial History, Arts, Culture, and Tourism Office",
      acronym: "PHACTO",
      description: "This department promotes cultural heritage and tourism.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Cultural Heritage", "Tourism Development", "Arts and Culture"],
    },
    {
      id: "d6e7f8g9",
      name: "Provincial Human Resource Management Office",
      acronym: "PHRMO",
      description: "This department handles human resource management for the province.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Human Resource Management", "Personnel Administration", "Training and Development"],
    },
    {
      id: "h1i2j3k4",
      name: "Provincial Information Technology Office",
      acronym: "PITO",
      description: "This department is responsible for IT infrastructure and services.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["IT Infrastructure", "Software Development", "Network Services"],
    },
    {
      id: "l5m6n7o8",
      name: "Provincial Legal Office",
      acronym: "PLO",
      description: "This department provides legal services and support to the province.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Legal Services", "Litigation", "Legal Research"],
    },
    {
      id: "p9q0r1s2",
      name: "Provincial Planning and Development Office",
      acronym: "PPDO",
      description: "This department is responsible for planning and development initiatives.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Planning and Development", "Urban Planning", "Rural Development"],
    },
    {
      id: "t3u4v5w6",
      name: "Provincial Public Affairs Office",
      acronym: "PPAO",
      description: "This department handles public affairs and information.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Public Affairs", "Information Services", "Media Relations"],
    },
    {
      id: "x7y8z9a0",
      name: "Provincial Public Employment Service Office",
      acronym: "PPESO",
      description: "This department provides employment services and support.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Employment Services", "Job Placement", "Labor Market Information"],
    },
    {
      id: "b1c2d3e4",
      name: "Provincial Public Health Office",
      acronym: "PPHO",
      description: "This department is responsible for public health services and programs.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Public Health Services", "Health Programs", "Health Education"],
    },
    {
      id: "f5g6h7i8",
      name: "Provincial Social Welfare and Development Office",
      acronym: "PSWDO",
      description: "This department provides social welfare and development services.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Social Welfare Services", "Development Programs", "Family and Community Welfare"],
    },
    {
      id: "j9k0l1m2",
      name: "Provincial Treasurer's Office",
      acronym: "PTO",
      description: "This department handles treasury operations and management.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Treasury Operations", "Cash Management", "Investment Management"],
    },
    {
      id: "n3o4p5q6",
      name: "Provincial Veterinary Office",
      acronym: "PVO",
      description: "This department is responsible for animal health and welfare.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Animal Health", "Veterinary Services", "Animal Welfare"],
    },
    {
      id: "r7s8t9u0",
      name: "Provincial Youth and Sports Development Office",
      acronym: "PYSDO",
      description: "This department promotes youth development and sports.",
      dateCreated: "2020-01-01T08:00:00",
      divisions: ["Youth Development", "Sports Development", "Recreation and Leisure"],
    },
  ]