import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./mobile.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import ClientLayout from "@/components/layouts/client-layout";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { useEffect, useState } from "react";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PGSO",
  description: "Generated by create next app",
  metadataBase: new URL("https://dev.pgso.bpc-bsis4d.com"),
  viewport:
    "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="bg-base-100 text-base-content"
    >
      <head>
        <meta
          httpEquiv="Content-Security-Policy"
          content="
            default-src 'self' https: data:;
            script-src 'self' 'unsafe-inline' 'unsafe-eval';
            connect-src 'self' https:;
            img-src 'self' data: https:;
            style-src 'self' 'unsafe-inline' https: data:;
            font-src 'self' https: data:;
          "
        />
        <meta httpEquiv="X-Content-Type-Options" content="nosniff" />
        <meta name="referrer" content="no-referrer-when-downgrade" />
      </head>
      <body className={`${inter.className} app-container`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <ClientLayout>
              {children}
              <div className="fixed bottom-4 right-4 z-50">
                <ModeToggle />
              </div>
            </ClientLayout>
            <Toaster />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
