import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import ClientLayout from "@/components/layouts/ClientLayout";
import { Toaster } from "@/components/ui/toaster";
import { v4 as uuidv4 } from "uuid";
import ErrorBoundary from "@/components/error-boundary";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PGSO",
  description: "Generated by create next app",
  metadataBase: new URL("https://server.pgso.bpc-bsis4d.com"),
};

// Generate CSRF token
const generateCsrfToken = () => {
  return uuidv4();
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const csrfToken = generateCsrfToken();

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="bg-base-100 text-base-content"
    >
      <head>
        <meta name="csrf-token" content={csrfToken} />
        <meta
          httpEquiv="Content-Security-Policy"
          content="
            default-src 'self';
            script-src 'self' 'unsafe-inline' 'unsafe-eval';
            connect-src 'self' https://server.pgso.bpc-bsis4d.com https://dev.pgso.bpc-bst-cd.com;
            img-src 'self' data: https:;
            style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
            font-src 'self' https://fonts.gstatic.com;
          "
        />
        <meta httpEquiv="X-Content-Type-Options" content="nosniff" />
        <meta name="referrer" content="strict-origin-when-cross-origin" />
      </head>
      <body className={inter.className}>
        <ErrorBoundary>
          <SidebarProvider>
            <ClientLayout>{children}</ClientLayout>
            <Toaster />
          </SidebarProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
