import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css"
import { SidebarProvider } from "@/components/ui/sidebar"
import ClientLayout from "@/components/layouts/ClientLayout"
import { Toaster } from "@/components/ui/toaster";


const inter = Inter({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "PGSO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={inter.className}
      >
        <SidebarProvider>
          <ClientLayout>
            {children}
          </ClientLayout>
          <Toaster />
        </SidebarProvider>
      </body>
    </html>
  );
}
