name: Deploy Next.js to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload to Hostinger
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install lftp 
        run: sudo apt-get install -y lftp

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build
          path: out

      - name: Upload to Hostinger
        run: |
          lftp -c "set ftp:ssl-allow on; set ssl:verify-certificate false; open -u u665838367.pgso.bpc-bsis4d.com,o![EXNdJL[Z@+=7B ftp://145.223.108.80; mirror -Rev out/ ./ --ignore-time --parallel=10"

