name: Deploy Next.js to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Prepare standalone build
        run: |
          cp -r .next/static .next/standalone/.next/
          cp -r public .next/standalone/

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: .next/standalone

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install lftp 
        run: sudo apt-get install -y lftp

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build
          path: build

      - name: Create .htaccess
        run: |
          echo "<IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /dev/
            RewriteRule ^index\.html$ - [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-l
            RewriteRule . /dev/index.html [L]
          </IfModule>" > build/.htaccess

      - name: Upload to Hostinger
        run: |
          lftp -c "set ftp:ssl-allow on; set ssl:verify-certificate false; open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} ftp://145.223.108.80; mirror -Rev build/ /public_html/dev/ --exclude-glob default.php --ignore-time --parallel=10"